### ISSUE TITLE
[FEATURE] <...>A way to change the author to someone else

### ISSUE THREAD

**Issue by rioiswoof** [eclipseisoffline/bookcopy#5]
I'm a pretty sentimental person and someone wrote something for me on a book and I'd like to copy it with him still being the author. I've looked online and it looks like every update there's a different way to change the author thru command but I'm really dumb and can't figure it out. I'm sure there are other uses for this like for map purposes or something else, but I thought I'd lead with why I wanted this feature.

Hope you consider this :>

**Comment by eclipseisoffline** [comment]
Hi, unfortunately, the client control the author of a book, and since the mod is coded client-side, I'm unable to add this feature.

If you want to modify the author of a written book, there is a way to do that using the `/data` command, so you have to have access to operator commands/"cheats":

Make sure you have the book written and signed. Put the book in a chest, then stand on that chest, and run the following command:
`/data modify block ~ ~ ~ Items[{id:"minecraft:written_book"}].components."minecraft:written_book_content".author set value [NAME]`
For example, to change the author to the player "Alex":
`/data modify block ~ ~ ~ Items[{id:"minecraft:written_book"}].components."minecraft:written_book_content".author set value Alex`

This command should work in Minecraft 1.20.5 to 1.21.1. It's a good idea to make sure you have a copy of the book you're changing the author of, if the command somehow goes wrong the book could get corrupted.

Take care and stay safe, hopefully that helps!
